### ISSUE TITLE
[Feature Request] Add jxl(JPEG XL) support

### ISSUE THREAD

**Issue by tr7zw** [getmango/Mango#306]
**Is your feature request related to a problem? Please describe.**
It would be really nice to have support for https://jpeg.org/jpegxl/index.html (https://github.com/libjxl/libjxl) due to it's REALLY good file size.

**Describe the solution you'd like**
Bestcase have support to send out the jxl files to the browser(Browsers support it, but apparently not yet by default without enabling it). Also having an option to serverside on the fly turn them back into .png for clients to show.

**Describe a small use-case for this feature request**
This would decrease the library size multiple times. In my test(default settings), a simple Manga page got compressed from 1.86mb down to 228kb without any quality loss. That's about 8 times smaller! Some more numbers playing with the quality setting: 
100: 1.171mb(lossless version of the png)
80: 153kb with just small changes in the sub-pixel noise
50: 87kb(21x smaller!) with just a slight loss in fine details(but no apparent blocky artifacts like jpeg's, on a phone/normal zoom level basically not visible).
With on-the-fly server conversions, this process could become fully transparent to the end clients that might not support this feature, and if supported it can heavily save on bandwidth for mobile use-cases, while also turning an entire chapter into the size of one page in png format.

**Additional context**
``JPEG XL is in the final stages of standardization and its codestream and file format are frozen.``, so the fileformat itself is save, but currently the main implementation is only in C++. That works for me since for my tools I can use JNA in Java to use the .ddl/.so files, not 100% sure about Crystals abilities to do that. Worst case it needs to be expanded to be able to use external parsers/decoders(which would be possible with pr 305), or keep this issue in the back of the mind till it becomes possible.

Edit: also looks like tachiyomi added support last year https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.12.1
https://github.sre.pub/leechy/imgsupport can base as an example to auto fall back to .png in case jxl isn't supported?

**Comment by tr7zw** [comment]
Ok for sanity check also gave it a test with a zip containing only jxl files and currently it's not detected at all.

**Comment by tr7zw** [comment]
Just sending it would be an awesome start 👍

**Comment by tr7zw** [comment]
Did a test build with jxl added and everything works perfectly fine 👍 
Edge on PC: start with the jxl flag
Firefox on PC: Needs Nightly, enable flag in about:config
Chrome on Android: toggle flag in chrome://flags
Tachyomi: Works out of the box

Guess I'll now spend a moment creating a small tool to convert my entire lib to jxl.

**Comment by tr7zw** [comment]
Another small note for the readme: when trying to build mango on Windows, git will convert the linebreaks by default, causing compile errors with config.cr due to the ``\`` new lines. Maybe a small note for Windows users to set ``git config core.autocrlf false``.

**Comment by tr7zw** [comment]
Ok one issue I noticed, sometimes on first opening of a chapter, it loads all images with ``width=0, height=0`` (at least in chrome)
![grafik](https://user-images.githubusercontent.com/5133936/172265599-29f002bc-08c8-4c0c-9eca-d309f92c87b9.png)

After a Control+F5 it's fixed. (just F5 doesn't work)

**Comment by hkalexling** [comment]
I updated [the wiki](https://github.com/hkalexling/Mango/wiki/Platform-Support) to include the `core.autocrlf` config :)
