### ISSUE TITLE
[Bug Report] `mango.attribute` does not work correctly with certain strings.

### ISSUE THREAD

**Issue by Elastic1** [getmango/Mango#320]
**Describe the bug**
`mango.attribute` does not work correctly with certain strings.

**To Reproduce**
```js
var html = '<img src="data:image/svg+xml,<svg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 1 1 \'></svg>" data-src="https://example.com/1.jpg" class="size-full wp-image-105 aligncenter lazy image-vertical" alt="">'
var src = mango.attribute(html, 'data-src') // null (expected: https://example.com/1.jpg)
```
In my plugin, I currently deal with this by removing the `src="..."`
**Environment (please complete the following information):**
 - OS: CentOS Stream release 8
 - Browser: chrome
 - Mango Version: 0.6.2

**Comment by hkalexling** [comment]
Thanks for the bug report! `mango.attribute` uses an XML parser and it doesn't like the `<` and `>` characters in attribute values. I will replace it with a proper HTML parser and it should resolve the issue.
